name: stagexl_bitmapfont
version: 0.5.0+1
description: BitmapFont support for StageXL.
homepage: http://www.stagexl.org
publish_to: none

environment:
  sdk: '^3.4.0'

dependencies:
  stagexl:
    git:
      url: https://github.com/CEksal/StageXL
      ref: package-web
  web: ^1.0.0
  http: ^1.1.0

dev_dependencies:
  build_test: any
  build_runner: any
  build_web_compilers: any
